### PR TITLE
Adds Lea Verou's CSS Variables talk

### PR DESCRIPTION
**Pull request by ismamz**

### CODE REVIEW

**Comment by AllThingsSmitty** [comment]
This is definitely a good one, and I've thought about it a bunch in the last year. I was concerned about too many Lea talks on the list (although, her talks are popular because they are so great!). Let me think about this a bit more. Definitely a great topic, too!

**Comment by LeaVerou** [comment]
Too many?! There are none after (or before) 2013 in the list!
I’m finding it hard to believe that they peaked in 2013.

**Comment by AllThingsSmitty** [comment]
Huh, I thought I had more listed, but you're right those seem to taper off.

**Comment by AllThingsSmitty** [comment]
@ismamz I've reordered so David's talk comes after Lea's.

**Pull request merged**
